import { Inter } from 'next/font/google'
import './globals.css'
import { Metadata } from 'next'
import Sidebar from '@/components/Sidebar'
import { SessionProvider } from '@/components/sessionprovider'
import { getServerSession } from 'next-auth'

import Login from '@/components/Login'
import { authOptions } from './api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {session ? (
            <div className="flex h-screen">
              <div className="bg-gray-800 p-2 w-5/12 sm:w-1/3 md:w-2/6 lg:w-1/6 overflow-y-auto">
                <Sidebar />
              </div>

              <div className="w-7/12 sm:w-2/3 md:w-4/6 lg:w-5/6 bg-[#74AA9C] overflow-y-auto">
                {children}
              </div>
            </div>
          ) : (
            <Login />
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
